name: frontendappmovil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: any
  http: ^1.2.2
  intl: any
  location: ^7.0.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png